version: '3'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: frontend-image
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - three-tier-net


  backend:
    container_name: backend
    build:
      context: ./backend
    image: backend-image
    ports:
      - "3500:3500"
    env_file:
      - ./backend/.env
    networks:
      - three-tier-net


networks:
  three-tier-net:
    driver: bridge
